cgi.fix_pathinfo=0
expose_php=Off
memory_limit=512M
max_execution_time=300
max_input_time=300
post_max_size=210M
upload_max_filesize=200M

opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.revalidate_freq=0
